Repository opensearch-project/observability, pull requests merged in 2022-04, with the labels that each got.

#619 Tweak build.gradle to have the correct qualifiers in 2.0.0
  opensearch-observability/build.gradle
Labels: v2.0.0, release

#629 Fixes trace analytics invalid service map and increase span limit
  dashboards-observability/public/components/trace_analytics/components/traces/trace_view.tsx
  dashboards-observability/public/components/trace_analytics/requests/queries/traces_queries.ts
Labels: backport 1.3

#669 Fix test to check for empty event analytics
  dashboards-observability/.cypress/integration/app_analytics.spec.js
  dashboards-observability/.cypress/utils/app_constants.js
Labels: backport 2.0

#674 Add release notes for 2.0.0-rc1
  release-notes/opensearch-observability.release-notes-2.0.0.0-rc1.md
Labels: backport 2.0
