Repository opensearch-project/observability, pull requests merged in 2022-10, with the labels that each got.

#1060 Add release notes for 1.3.6
  release-notes/opensearch-observability.release-notes-1.3.6.0.md
Labels: backport 1.3

#1062 Update jackson to 2.13.4
  opensearch-observability/build.gradle
Labels: backport 1.x, backport 1.3, backport 2.0, backport 2.1, backport 2.2, backport 2.x, backport 2.3

#1066 Update Jackson to 2.13.4
  opensearch-observability/build.gradle
Labels: backport 1.3

#1068 Update release-notes for 1.3.6
  release-notes/opensearch-observability.release-notes-1.3.6.0.md
Labels: backport 1.3

#1115 add groupId to pluginzip publication
  opensearch-observability/build.gradle
Labels: v2.4.0, backport 2.x
