Repository opensearch-project/observability, pull requests merged in 2022-12, with the labels that each got.

#1313 Bump moment from 2.29.2 to 2.29.4
  dashboards-observability/public/components/custom_panels/panel_modules/visualization_container/__tests__/__snapshots__/visualization_container.test.tsx.snap
  dashboards-observability/yarn.lock
Labels: backport 1.x

#1315 [Backport/backport 1228 to 1.3] Bump minimatch to v3.0.5
  dashboards-observability/package.json
  dashboards-observability/yarn.lock
Labels: backport 1.x

#1316 FIX: update qs version
  dashboards-observability/package.json
  dashboards-observability/yarn.lock
Labels: backport 1.x

#1341 Add release notes for 1.3.7 release
  .github/workflows/dashboards-observability-test-and-build-workflow.yml
  release-notes/opensearch-observability.release-notes-1.3.7.0.md
Labels: backport 1.x

#1343 Adding release notes for 2.4.1
  release-notes/opensearch-observability.release-notes-2.4.1.0.md
Labels: backport 2.x, backport main

#1352 Removing explicit jackson dependencies
  opensearch-observability/build.gradle
Labels: backport main

#1353 Upgrade detekt for CVE fix to 1.22.0
  opensearch-observability/build.gradle
Labels: backport main
