Repository opensearch-project/observability, pull requests merged in 2023-03, with the labels that each got.

#1436 Automate releases based on tagging
  .github/workflows/auto-release.yml
  .github/workflows/enforce-labels.yml
Labels: infrastructure

#1449 Fix maven publish branches in workflow
  .github/workflows/maven-publish.yml
Labels: backport 1.x, backport 2.x

#1437 Fix main CI upstream opensearch imports and use maven repo instead of jenkins
  build.gradle
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/action/CreateObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/action/CreateObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/CreateObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/GetObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/action/GetObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/GetObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt
  src/main/kotlin/org/opensearch/observability/model/Application.kt
  src/main/kotlin/org/opensearch/observability/model/BaseModel.kt
  src/main/kotlin/org/opensearch/observability/model/BaseResponse.kt
  src/main/kotlin/org/opensearch/observability/model/Notebook.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectDataProperties.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectDoc.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectSearchResult.kt
  src/main/kotlin/org/opensearch/observability/model/OperationalPanel.kt
  src/main/kotlin/org/opensearch/observability/model/RestTag.kt
  src/main/kotlin/org/opensearch/observability/model/SavedQuery.kt
  src/main/kotlin/org/opensearch/observability/model/SavedVisualization.kt
  src/main/kotlin/org/opensearch/observability/model/ScheduledJobDoc.kt
  src/main/kotlin/org/opensearch/observability/model/SearchResults.kt
  src/main/kotlin/org/opensearch/observability/model/Timestamp.kt
  src/main/kotlin/org/opensearch/observability/model/XParser.kt
  src/main/kotlin/org/opensearch/observability/resthandler/RestResponseToXContentListener.kt
  src/main/kotlin/org/opensearch/observability/scheduler/ObservabilityJobParser.kt
  src/main/kotlin/org/opensearch/observability/util/Helpers.kt
  src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt
  src/test/kotlin/org/opensearch/observability/TestHelpers.kt
Labels: infrastructure

#1453 [Backport 1.x] Add maven publish workflow
  .github/workflows/maven-publish.yml
Labels: infrastructure

#1465 Bump SnakeYAML Version
  build.gradle
Labels: bug

#1446 add catalog meta info in the index template
  docs/API/README.md
  docs/API/swagger.yaml
  docs/Integration-API.md
  docs/Integration-fields-mapping.md
  docs/Integration-loading.md
  docs/Integration-plugin-tasks.md
  docs/Integration-publishing.md
  docs/Integration-structure.md
  docs/Integration-verification.md
  docs/Integrations.md
  docs/Simple-schema.md
  docs/TableOfContent.md
  docs/img/data-prepper.png
  docs/img/integration-architecture.png
  docs/img/integration-component-layout.png
  docs/img/integration-loading-lifecycle.png
  docs/observability/Naming-convention.md
  integrations/README.md
  integrations/nginx/config.json
  integrations/nginx/info/README.md
  integrations/nginx/info/fluet-bit/README.md
  integrations/nginx/info/fluet-bit/fluent-bit.conf
  integrations/nginx/info/fluet-bit/fluentbit.png
  integrations/nginx/info/nginx.png
  integrations/nginx/samples/README.md
  integrations/nginx/schema/README.md
  integrations/nginx/schema/fluent-bit/parsers.conf
  integrations/nginx/test/README.md
  schema/README.md
  schema/observability/catalog.json
  schema/observability/logs/logs.mapping
  schema/observability/metrics/metrics.mapping
  schema/observability/metrics/metrics.schema
  schema/observability/traces/services.mapping
  schema/observability/traces/traces.mapping
  schema/observability/traces/traces.schema
  schema/system/catalog.schema
  schema/system/integration-instance.schema
  schema/system/integration.schema
  schema/system/integrations-template-list.schema
  schema/system/samples/catalog.json
  schema/system/samples/integration-instance.json
  schema/system/samples/integration.json
  schema/system/samples/integrations-template-list.json
Labels: documentation, integration

#1483 [BACKPORT 2.x] Fix 2.x imports
  build.gradle
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/action/CreateObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/action/CreateObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/CreateObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/GetObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/action/GetObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/GetObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt
  src/main/kotlin/org/opensearch/observability/model/Application.kt
  src/main/kotlin/org/opensearch/observability/model/BaseModel.kt
  src/main/kotlin/org/opensearch/observability/model/BaseResponse.kt
  src/main/kotlin/org/opensearch/observability/model/Notebook.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectDataProperties.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectDoc.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectSearchResult.kt
  src/main/kotlin/org/opensearch/observability/model/OperationalPanel.kt
  src/main/kotlin/org/opensearch/observability/model/RestTag.kt
  src/main/kotlin/org/opensearch/observability/model/SavedQuery.kt
  src/main/kotlin/org/opensearch/observability/model/SavedVisualization.kt
  src/main/kotlin/org/opensearch/observability/model/ScheduledJobDoc.kt
  src/main/kotlin/org/opensearch/observability/model/SearchResults.kt
  src/main/kotlin/org/opensearch/observability/model/Timestamp.kt
  src/main/kotlin/org/opensearch/observability/model/XParser.kt
  src/main/kotlin/org/opensearch/observability/resthandler/RestResponseToXContentListener.kt
  src/main/kotlin/org/opensearch/observability/scheduler/ObservabilityJobParser.kt
  src/main/kotlin/org/opensearch/observability/util/Helpers.kt
  src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt
  src/test/kotlin/org/opensearch/observability/TestHelpers.kt
Labels: infrastructure

#1470 Rename all SSO references to SS4O
  docs/API/swagger.yaml
  docs/Integration-API.md
  docs/Integration-fields-mapping.md
  docs/Integration-plugin-tasks.md
  docs/Integration-structure.md
  docs/Integration-verification.md
  docs/observability/Naming-convention.md
  integrations/nginx/assets/display/ss4o-logs-dashboard-new.ndjson
  integrations/nginx/info/README.md
  integrations/nginx/info/fluent-bit/README.md
  integrations/nginx/info/fluent-bit/fluent-bit.conf
  integrations/nginx/info/fluent-bit/fluentbit.png
  integrations/nginx/samples/README.md
  integrations/nginx/samples/preloaded/README.md
  integrations/nginx/schema/README.md
  integrations/nginx/test/README.md
  integrations/nginx/test/fluent-bit/fluent-bit.conf
  schema/observability/README.md
  schema/observability/logs/Usage.md
  schema/observability/logs/logs.mapping
  schema/observability/metrics/metrics.mapping
  schema/observability/metrics/samples/load_samples.md
  schema/observability/traces/samples/load_samples.md
  schema/observability/traces/traces.mapping
  schema/system/samples/integration-instance.json
  src/main/kotlin/org/opensearch/observability/index/ObservabilityMetricsIndex.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityTracesIndex.kt
  src/test/kotlin/org/opensearch/observability/rest/AssemblyValidationIT.kt
Labels: documentation, infrastructure
