Repository opensearch-project/observability, pull requests merged in 2023-08, with the labels that each got.

#1580 Backport/backport 1572 to 2.x
  build.gradle
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/action/CreateObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/CreateObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/GetObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/GetObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/ObservabilityActions.kt
  src/main/kotlin/org/opensearch/observability/action/PluginBaseAction.kt
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityQueryHelper.kt
  src/main/kotlin/org/opensearch/observability/metrics/RollingCounter.kt
  src/main/kotlin/org/opensearch/observability/model/Application.kt
  src/main/kotlin/org/opensearch/observability/model/BaseModel.kt
  src/main/kotlin/org/opensearch/observability/model/BaseResponse.kt
  src/main/kotlin/org/opensearch/observability/model/Notebook.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectDataProperties.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectDoc.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectSearchResult.kt
  src/main/kotlin/org/opensearch/observability/model/OperationalPanel.kt
  src/main/kotlin/org/opensearch/observability/model/SavedQuery.kt
  src/main/kotlin/org/opensearch/observability/model/SavedVisualization.kt
  src/main/kotlin/org/opensearch/observability/model/SearchResults.kt
  src/main/kotlin/org/opensearch/observability/model/Timestamp.kt
  src/main/kotlin/org/opensearch/observability/resthandler/ObservabilityRestHandler.kt
  src/main/kotlin/org/opensearch/observability/resthandler/ObservabilityStatsRestHandler.kt
  src/main/kotlin/org/opensearch/observability/resthandler/RestResponseToXContentListener.kt
  src/main/kotlin/org/opensearch/observability/security/UserAccessManager.kt
  src/main/kotlin/org/opensearch/observability/util/Helpers.kt
  src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt
  src/test/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectResponseTests.kt
  src/test/kotlin/org/opensearch/observability/bwc/TABackwardCompatibilityIT.kt
  src/test/kotlin/org/opensearch/observability/rest/AssemblyValidationIT.kt
  src/test/kotlin/org/opensearch/observability/rest/CreateObjectIT.kt
  src/test/kotlin/org/opensearch/observability/rest/DeleteObjectIT.kt
  src/test/kotlin/org/opensearch/observability/rest/GetObjectIT.kt
  src/test/kotlin/org/opensearch/observability/rest/UpdateObjectIT.kt
Labels: maintenance

#1527 add ani to maintainers and codeowners
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: maintenance

#1582 fix 2.x build
  src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityIntegrationsIndex.kt
  src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt
Labels: maintenance

#1584 Add release notes for 1.3.12
  release-notes/opensearch-observability.release-notes-1.3.12.0.md
Labels: backport 2.x, backport main, maintenance

#1590 Fix from upstream core.action changes
  build.gradle
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/action/PluginBaseAction.kt
  src/main/kotlin/org/opensearch/observability/model/BaseResponse.kt
  src/main/kotlin/org/opensearch/observability/util/SecureIndexClient.kt
Labels: maintenance

#1591 Fix from upstream core.action changes (#1590)
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/action/PluginBaseAction.kt
  src/main/kotlin/org/opensearch/observability/model/BaseResponse.kt
  src/main/kotlin/org/opensearch/observability/util/SecureIndexClient.kt
Labels: maintenance

#1587 Update backport CI, add PR merged condition
  .github/workflows/backport.yml
Labels: backport 2.x, infrastructure

#1593 [Backport 2.x] Update backport CI, add PR merged condition
  .github/workflows/backport.yml
Labels: infrastructure

#1598 Pull jackson,mockito versions from upstream
  build.gradle
Labels: maintenance
