Repository opensearch-project/observability, pull requests merged in 2023-05, with the labels that each got.

#1518 Merge Gradle fixes into integrations branch
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/kotlin/org/opensearch/integrations/IntegrationsPlugin.kt
  src/main/kotlin/org/opensearch/integrations/resthandler/IntegrationStoreRestHandler.kt
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/test/kotlin/org/opensearch/integrations/rest/GetStoreIT.kt
Labels: infrastructure

#1521 Add Integration Index to Demo
  src/main/kotlin/org/opensearch/integrations/action/CreateIntegrationAction.kt
  src/main/kotlin/org/opensearch/integrations/action/CreateIntegrationRequest.kt
  src/main/kotlin/org/opensearch/integrations/action/CreateIntegrationResponse.kt
  src/main/kotlin/org/opensearch/integrations/index/IntegrationIndex.kt
  src/main/kotlin/org/opensearch/integrations/model/BaseModel.kt
  src/main/kotlin/org/opensearch/integrations/model/BaseObjectData.kt
  src/main/kotlin/org/opensearch/integrations/model/Integration.kt
  src/main/kotlin/org/opensearch/integrations/resthandler/IntegrationStoreRestHandler.kt
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/resources/integrations-mapping.yml
  src/main/resources/integrations-settings.yml
  src/test/kotlin/org/opensearch/integrations/model/IntegrationObjectTests.kt
  src/test/kotlin/org/opensearch/integrations/rest/CreateIntegrationIT.kt
Labels: enhancement

#1500 Update collection feeds
  docs/API/API.png
  docs/API/README.md
  docs/API/swagger.yaml
  docs/Integration-API.md
  docs/Integration-plugin-tasks.md
  docs/Integration-structure.md
  docs/schema/observability/logs/README.md
  docs/schema/observability/logs/cloud.md
  docs/schema/observability/logs/communication.md
  docs/schema/observability/logs/container.md
  docs/schema/observability/logs/http.md
  docs/schema/observability/logs/logs.md
  docs/schema/system/samples/integration.json
  integrations/README.md
  integrations/nginx/assets/README.md
  integrations/nginx/assets/channels/slack.json
  integrations/nginx/assets/monitor/ErrorPerMinute.json
  integrations/nginx/assets/monitor/RequestsPerMinute.json
  integrations/nginx/config.json
  integrations/nginx/schema/fields.json
  integrations/service-map/assets/README.md
  integrations/service-map/assets/mapping/jaeger-services.mapping
  integrations/service-map/assets/mapping/jaeger-traces.mapping
  integrations/service-map/assets/queries/getTraceGroupPercentilesQuery.json
  integrations/service-map/assets/scripts/getPayloadQuery.json
  integrations/service-map/assets/scripts/getServiceBreakdownQuery.json
  integrations/service-map/assets/scripts/getSpanDetailQuery.json
  integrations/service-map/assets/scripts/getSpanFlyoutQuery.json
  integrations/service-map/assets/scripts/getSpansQuery.json
  integrations/service-map/assets/scripts/getTracesQuery.json
  integrations/service-map/assets/scripts/getValidTraceIdsQuery.json
  integrations/service-map/config.json
  integrations/service-map/info/providers/data-prepper/README.md
  integrations/service-map/info/providers/data-prepper/dataPrepper.svg
  integrations/service-map/info/providers/jaeger/README.md
  integrations/service-map/info/providers/jaeger/jaeger-logo.png
  integrations/service-map/samples/preloaded/README.md
  integrations/service-map/samples/preloaded/data_prepper_bulk_traces.json
  integrations/service-map/samples/preloaded/jaeger_bulk_traces.json
  src/main/resources/schema/observability/logs/logs.mapping
  src/main/resources/schema/observability/logs/logs.schema
  src/main/resources/schema/system/integration.schema
Labels: documentation, design, v2.8.0, integration

#1525 fix CVE-2022-45688
  build.gradle
Labels: dependencies, security fix

#1526 fix CVE-2023-30861
  integrations/nginx/test/flask-app/requirements.txt
Labels: security fix

#1528 Sync Integrations with Upstream
  src/main/kotlin/org/opensearch/integrations/action/CreateIntegrationAction.kt
  src/main/kotlin/org/opensearch/integrations/action/CreateIntegrationRequest.kt
  src/main/kotlin/org/opensearch/integrations/action/CreateIntegrationResponse.kt
  src/main/kotlin/org/opensearch/integrations/action/GetIntegrationObjectAction.kt
  src/main/kotlin/org/opensearch/integrations/action/GetIntegrationObjectRequest.kt
  src/main/kotlin/org/opensearch/integrations/action/GetIntegrationObjectResponse.kt
  src/main/kotlin/org/opensearch/integrations/index/IntegrationIndex.kt
  src/main/kotlin/org/opensearch/integrations/index/IntegrationQueryHelper.kt
  src/main/kotlin/org/opensearch/integrations/model/Integration.kt
  src/main/kotlin/org/opensearch/integrations/model/IntegrationInstance.kt
  src/main/kotlin/org/opensearch/integrations/model/IntegrationObjectDataProperties.kt
  src/main/kotlin/org/opensearch/integrations/model/IntegrationObjectDoc.kt
  src/main/kotlin/org/opensearch/integrations/model/IntegrationObjectSearchResult.kt
  src/main/kotlin/org/opensearch/integrations/model/IntegrationObjectType.kt
  src/main/kotlin/org/opensearch/integrations/model/IntegrationTemplate.kt
  src/main/kotlin/org/opensearch/integrations/model/RestTag.kt
  src/main/kotlin/org/opensearch/integrations/model/SearchResults.kt
  src/main/kotlin/org/opensearch/integrations/model/XParser.kt
  src/main/kotlin/org/opensearch/integrations/resthandler/IntegrationRestHandler.kt
  src/main/kotlin/org/opensearch/integrations/resthandler/IntegrationStoreRestHandler.kt
  src/main/kotlin/org/opensearch/integrations/security/SecurityAccess.kt
  src/main/kotlin/org/opensearch/integrations/security/UserAccessManager.kt
  src/main/kotlin/org/opensearch/integrations/util/FieldParser.kt
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/resources/nginx.json
  src/test/kotlin/org/opensearch/integrations/model/IntegrationInstanceTests.kt
  src/test/kotlin/org/opensearch/integrations/model/IntegrationTemplateTests.kt
  src/test/kotlin/org/opensearch/integrations/rest/CreateIntegrationIT.kt
  src/test/kotlin/org/opensearch/integrations/rest/DemoIT.kt
  src/test/kotlin/org/opensearch/integrations/rest/GetIntegrationIT.kt
  src/test/kotlin/org/opensearch/integrations/util/FieldParserTests.kt
Labels: enhancement, integration

#1531 bumb bwc version to 2.8
  build.gradle
Labels: ci, backport 2.x, infrastructure

#1536 fix guava jar hell issue
  build.gradle
Labels: infrastructure

#1539 fix ci
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectRequest.kt
Labels: infrastructure

#1543 Force resolution snakeyaml to 2.0
  build.gradle
Labels: dependencies, security fix

#1544 Add release notes for 2.8
  release-notes/opensearch-observability.release-notes-2.8.0.0.md
Labels: backport 2.x, backport 2.8
