Repository opensearch-project/observability, pull requests merged in 2023-07, with the labels that each got.

#1565 Release Notes 2.9
  release-notes/opensearch-observability.release-notes-2.9.0.0.md
Labels: documentation, release

#1563 [BACKPORT 2.x] remove job scheduler (#1560)
  build.gradle
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/model/RestTag.kt
  src/main/kotlin/org/opensearch/observability/model/ScheduledJobDoc.kt
  src/main/kotlin/org/opensearch/observability/resthandler/SchedulerRestHandler.kt
  src/main/kotlin/org/opensearch/observability/scheduler/ObservabilityJobParser.kt
  src/main/kotlin/org/opensearch/observability/scheduler/ObservabilityJobRunner.kt
  src/test/kotlin/org/opensearch/observability/ObservabilityPluginIT.kt
Labels: infrastructure

#1572 Resolve build issue
  build.gradle
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/action/CreateObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/CreateObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/GetObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/GetObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/action/ObservabilityActions.kt
  src/main/kotlin/org/opensearch/observability/action/PluginBaseAction.kt
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectRequest.kt
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectResponse.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityQueryHelper.kt
  src/main/kotlin/org/opensearch/observability/metrics/RollingCounter.kt
  src/main/kotlin/org/opensearch/observability/model/Application.kt
  src/main/kotlin/org/opensearch/observability/model/BaseModel.kt
  src/main/kotlin/org/opensearch/observability/model/BaseResponse.kt
  src/main/kotlin/org/opensearch/observability/model/Notebook.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectDataProperties.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectDoc.kt
  src/main/kotlin/org/opensearch/observability/model/ObservabilityObjectSearchResult.kt
  src/main/kotlin/org/opensearch/observability/model/OperationalPanel.kt
  src/main/kotlin/org/opensearch/observability/model/SavedQuery.kt
  src/main/kotlin/org/opensearch/observability/model/SavedVisualization.kt
  src/main/kotlin/org/opensearch/observability/model/SearchResults.kt
  src/main/kotlin/org/opensearch/observability/model/Timestamp.kt
  src/main/kotlin/org/opensearch/observability/resthandler/ObservabilityRestHandler.kt
  src/main/kotlin/org/opensearch/observability/resthandler/ObservabilityStatsRestHandler.kt
  src/main/kotlin/org/opensearch/observability/resthandler/RestResponseToXContentListener.kt
  src/main/kotlin/org/opensearch/observability/security/UserAccessManager.kt
  src/main/kotlin/org/opensearch/observability/util/Helpers.kt
  src/test/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectResponseTests.kt
  src/test/kotlin/org/opensearch/observability/bwc/TABackwardCompatibilityIT.kt
  src/test/kotlin/org/opensearch/observability/rest/CreateObjectIT.kt
  src/test/kotlin/org/opensearch/observability/rest/DeleteObjectIT.kt
  src/test/kotlin/org/opensearch/observability/rest/GetObjectIT.kt
  src/test/kotlin/org/opensearch/observability/rest/UpdateObjectIT.kt
Labels: maintenance
