Repository opensearch-project/observability, pull requests merged in 2023-02, with the labels that each got.

#1417 Add publish snapshots to maven via GHA
  .github/workflows/maven-publish.yml
  build.gradle
  settings.gradle
Labels: backport 2.x

#1424 2.6 release notes
  release-notes/opensearch-observability.release-notes-2.6.0.0.md
Labels: backport 2.x, backport main

#1427 Support sso metrics & traces schema
  MAINTAINERS.md
  release-notes/opensearch-observability.release-notes-2.6.0.0.md
  schema/README.md
  schema/metrics/README.md
  schema/metrics/metrics-mapping.json
  schema/metrics/metrics.schema
  schema/metrics/samples/gauge.json
  schema/metrics/samples/histogram.json
  schema/metrics/samples/load_samples.md
  schema/metrics/samples/sum.json
  schema/traces/README.md
  schema/traces/samples/load_samples.md
  schema/traces/samples/traceA.json
  schema/traces/samples/traceB.json
  schema/traces/samples/traceC.json
  schema/traces/traces-mapping.json
  schema/traces/traces.schema
  scripts/build.sh
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityMetricsIndex.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityTracesIndex.kt
  src/main/resources/metrics-mapping-template.json
  src/main/resources/traces-mapping-template.json
  src/test/kotlin/org/opensearch/observability/ObservabilityPluginIT.kt
  src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt
  src/test/kotlin/org/opensearch/observability/rest/AssemblyValidationIT.kt
Labels: documentation, v2.6.0
