Repository opensearch-project/observability, pull requests merged in 2023-09, with the labels that each got.

#1600 Updates demo certs used in integ tests
  src/test/resources/security/sample.pem
  src/test/resources/security/test-kirk.jks
Labels: backport 2.x, maintenance, v2.10.0

#1602 add 2.10 release notes
  release-notes/opensearch-observability.release-notes-2.10.0.0.md
Labels: documentation

#1620 Bump BWC version to 2.11
  build.gradle
Labels: maintenance

#1626 Updates demo certs used in integ tests
  src/test/resources/security/sample.pem
  src/test/resources/security/test-kirk.jks
Labels: backport 2.x, infrastructure
