Repository opensearch-project/observability, pull requests merged in 2024-03, with the labels that each got.

#1810 [Release notes] Add 2.13 release notes
  build.gradle
  release-notes/opensearch-observability.release-notes-2.13.0.0.md
Labels: backport 2.x, infrastructure

#1811 [Release notes] backport 2.13 release notes to 2.x
  release-notes/opensearch-observability.release-notes-2.13.0.0.md
Labels: infrastructure

#1806 Updates sample cert and admin keystore
  src/test/resources/security/sample.pem
  src/test/resources/security/test-kirk.jks
Labels: backport 2.x, maintenance, backport 2.13
