Repository opensearch-project/observability, pull requests merged in 2024-06, with the labels that each got.

#1838 Bump bwc version
  build.gradle
Labels: maintenance

#1837 Register system index descriptors through SystemIndexPlugin.getSystemIndexDescriptors
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt
Labels: enhancement, backport 2.x

#1840 [Backport 2.x] Register system index descriptors through SystemIndexPlugin.getSystemIndexDescriptors (#1837)
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt
Labels: enhancement
