Repository opensearch-project/observability, pull requests merged in 2024-02, with the labels that each got.

#1792 [SECURITY] CVE-2023-6378 and CVE-2023-6481 fixes
  build.gradle
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/metrics/Metrics.kt
  src/main/kotlin/org/opensearch/observability/model/SavedQuery.kt
  src/main/kotlin/org/opensearch/observability/model/SavedVisualization.kt
  src/main/kotlin/org/opensearch/observability/model/Timestamp.kt
  src/main/kotlin/org/opensearch/observability/settings/PluginSettings.kt
  src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt
  src/test/kotlin/org/opensearch/observability/TestHelpers.kt
Labels: security fix, backport 2.x, backport 2.12

#1794 [Backport 2.12] bumping ktlint and resolving conflicts (#1792)
  build.gradle
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/metrics/Metrics.kt
  src/main/kotlin/org/opensearch/observability/model/SavedQuery.kt
  src/main/kotlin/org/opensearch/observability/model/SavedVisualization.kt
  src/main/kotlin/org/opensearch/observability/model/Timestamp.kt
  src/main/kotlin/org/opensearch/observability/settings/PluginSettings.kt
  src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt
  src/test/kotlin/org/opensearch/observability/TestHelpers.kt
Labels: security fix, infrastructure

#1793 [Backport 2.x] bumping ktlint and resolving conflicts (#1792)
  build.gradle
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/metrics/Metrics.kt
  src/main/kotlin/org/opensearch/observability/model/SavedQuery.kt
  src/main/kotlin/org/opensearch/observability/model/SavedVisualization.kt
  src/main/kotlin/org/opensearch/observability/model/Timestamp.kt
  src/main/kotlin/org/opensearch/observability/settings/PluginSettings.kt
  src/test/kotlin/org/opensearch/observability/PluginRestTestCase.kt
  src/test/kotlin/org/opensearch/observability/TestHelpers.kt
Labels: security fix, infrastructure

#1795 [Security] Manually Force Secure logback Dependencies
  build.gradle
Labels: security fix, backport 2.x, infrastructure, backport 2.12

#1800 Added release notes for 2.12
  release-notes/opensearch-observability.release-notes-2.12.0.0.md
Labels: backport 2.x, maintenance, backport 2.12
