Repository opensearch-project/observability, pull requests merged in 2024-04, with the labels that each got.

#1819 update bwc version to 2.14.0
  build.gradle
Labels: maintenance

#1821 tenancy access control
  DEVELOPER_GUIDE.md
  README.md
  src/main/kotlin/org/opensearch/observability/security/UserAccessManager.kt
Labels: enhancement, backport 2.x

#1823 Adding release notes for 2.14
  release-notes/opensearch-observability.release-notes-2.14.0.0.md
Labels: backport 2.x, maintenance, backport 2.14
