Repository opensearch-project/observability, pull requests merged in 2025-02, with the labels that each got.

#1896 Add release notes for 2.19.0
  release-notes/opensearch-observability.release-notes-2.19.0.0.md
Labels: maintenance

#1905 [2.19] bump logback to 1.5.16
  build.gradle
Labels: backport main, maintenance

#1904 Bump version 3.0.0-alpha1-SNAPSHOT
  build.gradle
  src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt
  src/main/kotlin/org/opensearch/observability/action/CreateObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/action/DeleteObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/action/GetObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/action/PluginBaseAction.kt
  src/main/kotlin/org/opensearch/observability/action/UpdateObservabilityObjectAction.kt
  src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt
  src/main/kotlin/org/opensearch/observability/resthandler/ObservabilityRestHandler.kt
  src/main/kotlin/org/opensearch/observability/resthandler/ObservabilityStatsRestHandler.kt
  src/main/kotlin/org/opensearch/observability/util/SecureIndexClient.kt
Labels: maintenance

#1909 Bump jdk to 21 for maven snapshot build
  .github/workflows/maven-publish.yml
  MAINTAINERS.md
Labels: maintenance

#1910 add release notes for 2.19.1 release
  release-notes/opensearch-observability.release-notes-2.19.1.0.md
Labels: backport 2.19
